### ISSUE TITLE
Auto Assignment not working

### ISSUE THREAD

**Issue by bschultz** [versx/ControllerJS#9]
```
[AssignmentController] Assigning device iPhone6AW1 to Quests
(node:95574) Warning: Accessing non-existent property 'instance' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95574) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setup' of undefined
    at InstanceController.removeDeviceByName (/Users/bschultz/development/workspaces/other/ControllerJS/src/controllers/instance-controller.js:184:45)
    at InstanceController.removeDevice (/Users/bschultz/development/workspaces/other/ControllerJS/src/controllers/instance-controller.js:174:20)
    at AssignmentController.triggerAssignment (/Users/bschultz/development/workspaces/other/ControllerJS/src/controllers/assignment-controller.js:79:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:95574) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95574) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by versx** [comment]
Rip circular dependency :sob:

**Comment by bschultz** [comment]
Seems to work now
